olx/account/urls.py
from django.urls import path
from django.contrib.auth.views import login as auth_view
from . import views

app_name='account'

urlpatterns = [
    # path('login/', auth_view.LoginView.as_view(), name='login'),
    # path('password_change/', auth_view.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_view.LoginView.as_view(), name='password_change_done'),
    # path('password_reset/', auth_view.LoginView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_view.LoginView.as_view(), name='password_reset_done'),
    # path('password_reset/confirmed/<uid64>/<token>/', auth_view.LoginView.as_view(), name='password_reset_confirm'),
    # path('password_reset/complete/', auth_view.LoginView.as_view(), name='password_reset_complete'),
]

olx/olx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products'))
    # path('account/', include('account.urls', namespace='account')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx/product/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_category'),
    path('<slug:product_slug>', views.product_detail, name='product_detail'),
]

olx/account/models.py
from django.db import models

# Create your models here.

olx/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class Product(models.Model):
    CONDITION_TYPE=(('New', 'New'), ('Used', 'Used'))

    name=models.CharField(max_length=100)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    category=models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    brand=models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
    description=models.TextField(max_length=1000)
    condition=models.CharField(max_length=100, choices=CONDITION_TYPE)
    price=models.DecimalField(max_digits=15, decimal_places=5)
    image=models.ImageField(upload_to='main_product/', blank=True, null=True)
    created=models.DateTimeField(default=timezone.now)
    slug=models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug=slugify(self.name)
            super().save(*args, **kwargs)


class Category(models.Model):
    category_name=models.CharField(max_length=50)
    image=models.ImageField(upload_to='products/', blank=True, null=True)
    slug=models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name='Category'
        verbose_name_plural='Categories'

    def __str__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug=slugify(self.category_name)
            super().save(*args, **kwargs)


class Brand(models.Model):
    brand_name=models.CharField(max_length=50)

    class Meta:
        verbose_name='Brand'
        verbose_name_plural='Brands'

    def __str__(self):
        return self.brand_name


class ProductImages(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.product.name

olx/account/views.py
from django.shortcuts import render

# Create your views here.

olx/product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductImages, Category
from django.core.paginator import Paginator
from django.db.models import Count, Q


# Create your views here.
def product_list(request, category_slug=None):
    category=None
    product_list=Product.objects.all()
    category_list=Category.objects.annotate(total_products=Count('product'))
    if category_slug:
        category=get_object_or_404(Category, slug=category_slug)
        product_list=product_list.filter(category=category)
    search_query=request.GET.get('q')
    if search_query:
        product_list=product_list.filter(Q(name__icontains=search_query)|
                                        Q(description__icontains=search_query)|
                                        Q(condition__icontains=search_query)|
                                        Q(brand__brand_name__icontains=search_query)|
                                        Q(category__category_name__icontains=search_query))
    paginator = Paginator(product_list, 1)
    page_number = request.GET.get('page')
    product_list = paginator.get_page(page_number)
    context={'product_list':product_list, 'category_list':category_list, 'category':category} 
    return render(request, 'product/product_list.html', context)

def product_detail(request, product_slug):
    product_detail=get_object_or_404(Product, slug=product_slug)
    product_images=ProductImages.objects.filter(product=product_detail)
    context={'product_detail':product_detail, 'product_images':product_images}
    return render(request, 'product/product_detail.html', context)

olx/product/templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--single-page-->
<div class="single-page main-grid-border">
	<div class="container">
		<ol class="breadcrumb" style="margin-bottom: 5px;">
			<li><a href="index.html">Home</a></li>
			<li><a href="all-classifieds.html">All Ads</a></li>
			<li class="active"><a href="mobiles.html">Mobiles</a></li>
			<li class="active">Mobile Phone</li>
		</ol>
		<div class="product-desc">
			<div class="col-md-7 product-view">
				<h2>{{product_detail.name}}</h2>
				<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at {{product_detail.created}}, Ad ID: 987654321</p>
				<div class="flexslider">
					<ul class="slides">
					{% for image in product_images %}
						<li data-thumb="{{image.image.url}}">
							<img src="{{image.image.url}}" />
						</li>
					{% endfor %}
					</ul>
				</div>
				<!-- FlexSlider -->
				<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
				<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
				<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
						$('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
						});
					});
				</script>
				<!-- //FlexSlider -->
				<div class="product-details">
					<h4>Brand : <a href="#">{{product_detail.brand}}</a></h4>
					<h4>Views : <strong>150</strong></h4>
					<p><strong>Summary</strong>{{product_detail.description}}</p>
				
				</div>
			</div>
			<div class="col-md-5 product-details-grid">
				<div class="item-price">
					<div class="product-price">
						<p class="p-price">Price</p>
						<h3 class="rate">$ {{product_detail.price}}</h3>
						<div class="clearfix"></div>
					</div>
					<div class="condition">
						<p class="p-price">{{product_detail.condition}}</p>
						<h4>Good</h4>
						<div class="clearfix"></div>
					</div>
					<div class="itemtype">
						<p class="p-price">Item Type</p>
						<h4>{{product_detail.category}}</h4>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="interested text-center">
					<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
					<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
				</div>
					<div class="tips">
					<h4>Safety Tips for Buyers</h4>
						<ol>
							<li><a href="#">Contrary to popular belief.</a></li>
						</ol>
					</div>
			</div>
		<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--//single-page-->
{% endblock content %}

olx/product/templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Products -->
<div class="total-ads main-grid-border">
	<div class="container">
		<div class="select-box">
			<div class="browse-category ads-list">
				<label>Browse Categories</label>
				<select class="selectpicker show-tick" data-live-search="true">
					<option data-tokens="Mobiles">All</option>
					<option data-tokens="Mobiles">Mobiles</option>
					<option data-tokens="Electronics & Appliances">Electronics & Appliances</option>
					<option data-tokens="Cars">Cars</option>
					<option data-tokens="Bikes">Bikes</option>
					<option data-tokens="Furniture">Furniture</option>
					<option data-tokens="Pets">Pets</option>
					<option data-tokens="Books, Sports & Hobbies">Books, Sports & Hobbies</option>
					<option data-tokens="Fashion">Fashion</option>
					<option data-tokens="Kids">Kids</option>
					<option data-tokens="Services">Services</option>
					<option data-tokens="Jobs">Jobs</option>
					<option data-tokens="Real Estate">Real Estate</option>
				</select>
			</div>
			<div class="search-product ads-list">
				<label>Search for a specific product</label>
				<div class="search">
					<div id="custom-search-input">
					<div class="input-group">
						<input type="text" class="form-control input-lg" placeholder="Buscar" />
						<span class="input-group-btn">
							<button class="btn btn-info btn-lg" type="button">
								<i class="glyphicon glyphicon-search"></i>
							</button>
						</span>
					</div>
				</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="all-categories">
			<h3> Select your category and find the perfect ad</h3>
			<ul class="all-cat-list">
			{% for category in category_list %}
				<li><a href="{% url 'products:product_list_category' category.slug %}">{{category.category_name}} <span class="num-of-ads">({{category.total_products}})</span></a></li>
			{% endfor %}
			</ul>
		</div>
		<ol class="breadcrumb" style="margin-bottom: 5px;">
			<li><a href="/">Home</a></li>
			<li class="active"><a href="{% url 'products:product_list' %}">All Ads</a></li>
			{% if cateory %}
				<li class="active">{{category}}</li>
			{% endif %}
		</ol>
		<div class="ads-grid">
			<div class="side-bar col-md-3">
				<div class="search-hotel">
				<h3 class="sear-head">Search</h3>
				<form method="GET" action="{% url 'products:product_list' %}">
				{% csrf_token %}
					<input type="text" name="q" value="Product name..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
					<input type="submit" value=" ">
				</form>
			</div>
			</div>
			<div class="ads-display col-md-9">
				<div class="wrapper">					
				<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					<ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
					<li role="presentation" class="active">
						<a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">
						<span class="text">All Ads</span>
						</a>
					</li>
					</ul>
					<div id="myTabContent" class="tab-content">
					<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						<div>
							<div id="container">
							<div class="clearfix"></div>
						<ul class="list">
							{% for product in product_list %}
								<a href="{% url 'products:product_detail' product.slug %}">
									<li>
									<img src="{{product.image.url}}" title="" alt="" />
									<section class="list-left">
									<h5 class="title">{{product.name}}</h5>
									<span class="adprice">${{product.price}}</span>
									<p class="catpath">{{product.description}}</p>
									</section>
									<section class="list-right">
									<span class="date">{{product.created}}</span>
									</section>
									<div class="clearfix"></div>
									</li> 
								</a>
							{% endfor %}
						</ul>
					</div>
						</div>
					</div>
						</div>
					</div>
						</div>
					</div>
					{% if product_list.has_other_pages %}
					<ul class="pagination pagination-sm">
						{% if product_list.has_previous %}
							<li><a href="?page={{ product_list.previous_page_number }}">Prev</a></li>
						{% else %}
							<li class="disabled"></li>
						{% endif %}
						{% for page in product_list.paginator.page_range %}
							{% if product_list.number == page %}
								<li><a href="">{{page}}</a></li>
							{% else %}
								<li><a href="?page={{page}}">{{page}}</a></li>
							{% endif %}
						{% endfor %}
						{% if product_list.has_next %}
							<li><a href="?page={{ product_list.next_page_number }}">Next</a></li>
						{% else %}
							<li class="disabled"></li>
						{% endif %}
					</ul>
					{% endif %}
					</div>
				</div>
			</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>	
</div>
<!-- // Products -->
{% endblock content %}

olx/templates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Resale a Business Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
<link href="{% static 'css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<!-- Source -->
<script src="{% static 'js/jquery.uls.data.js' %}"></script>
<script src="{% static 'js/jquery.uls.data.utils.js' %}"></script>
<script src="{% static 'js/jquery.uls.lcd.js' %}"></script>
<script src="{% static 'js/jquery.uls.languagefilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.regionfilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.core.js' %}"></script>
<script>
			$( document ).ready( function() {
				$( '.uls-trigger' ).uls( {
					onSelect : function( language ) {
						var languageName = $.uls.data.getAutonym( language );
						$( '.uls-trigger' ).text( languageName );
					},
					quickList: ['en', 'hi', 'he', 'ml', 'ta', 'fr'] //FIXME
				} );
			} );
		</script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="index.html"><span>Re</span>sale</a>
			</div>
			<div class="header-right">
				<a class="account" href="login.html">My Account</a>
			</div>
		</div>
	</div>
	<div class="main-banner banner text-center">
	  <div class="container">    
			<h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Resale</h1>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
			<a href="post-ad.html">Post Free Ad</a>
	  </div>
	</div>
		<!-- content-starts-here -->
		{% block content %}
		{% endblock content %}
		<!--footer section start-->		
		<footer>
			<div class="footer-top">
				<div class="container">
					<div class="foo-grids">
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<li><a href="howitworks.html">How it Works</a></li>						
								<li><a href="sitemap.html">Sitemap</a></li>
								<li><a href="faq.html">Faq</a></li>
								<li><a href="feedback.html">Feedback</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="typography.html">Shortcodes</a></li>
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<li><a href="regions.html">Locations Map</a></li>	
								<li><a href="terms.html">Terms of Use</a></li>
								<li><a href="popular-search.html">Popular searches</a></li>	
								<li><a href="privacy.html">Privacy Policy</a></li>	
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
									<div class="clearfix"></div>
								</ul>						
							</address>
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>
</html>